### ISSUE TITLE
Please create release tag

### ISSUE THREAD

**Issue by MartijnKaijser** [Montellese/visualization.vortex#6]
Could you create a version tag so we can add this to Krypton as fixed point?

**Comment by Montellese** [comment]
Done, see https://github.com/Montellese/visualization.vortex/releases/tag/v1.6.0. But TBH I wouldn't mind if someone else could take this over. I only have this repository because I did the cmake migration for binary addons. I don't have any clue of the actual code/implementation.

**Comment by MartijnKaijser** [comment]
Maybe just move it to xbmc repo where it's more visible?
